INSERT INTO `users`(`email`, `username`, `password`) VALUES ('coucou@coucou.com', 'coucou', 'coucou');
INSERT INTO `posts`(`user_id`, `title`, `date`, `img_id`) VALUES (1, 'fortnite le bon jeu', 1523548806, 'here_the_img_id');
INSERT INTO `posts`(`user_id`, `title`, `date`, `img_id`) VALUES (1, 'fortnite le bon jeu', 1523548806, 'here_the_img_id');
INSERT INTO `posts`(`user_id`, `title`, `date`, `img_id`) VALUES (1, 'fortnite le bon jeu', 1523548806, 'here_the_img_id');
INSERT INTO `posts`(`user_id`, `title`, `date`, `img_id`) VALUES (1, 'fortnite le bon jeu', 1523548806, 'here_the_img_id');
INSERT INTO `posts`(`user_id`, `title`, `date`, `img_id`) VALUES (1, 'fortnite le bon jeu', 1523548806, 'here_the_img_id');
INSERT INTO `posts`(`user_id`, `title`, `date`, `img_id`) VALUES (1, 'fortnite le bon jeu', 1523548806, 'here_the_img_id');
INSERT INTO `posts`(`user_id`, `title`, `date`, `img_id`) VALUES (1, 'fortnite le bon jeu', 1523548806, 'here_the_img_id');
INSERT INTO `posts`(`user_id`, `title`, `date`, `img_id`) VALUES (1, 'fortnite le bon jeu', 1523548806, 'here_the_img_id');
INSERT INTO `posts`(`user_id`, `title`, `date`, `img_id`) VALUES (1, 'fortnite le bon jeu', 1523548806, 'here_the_img_id');
INSERT INTO `posts`(`user_id`, `title`, `date`, `img_id`) VALUES (1, 'fortnite le bon jeu', 1523548806, 'here_the_img_id');
INSERT INTO `posts`(`user_id`, `title`, `date`, `img_id`) VALUES (1, 'fortnite le bon jeu', 1523548806, 'here_the_img_id');

INSERT INTO `comments`(`user_id`, `post_id`, `message`, `date`) VALUES (1, 1, 'fortnite le bon jeu 2', 1523548806);
INSERT INTO `comments`(`user_id`, `post_id`, `message`, `date`) VALUES (1, 1, 'fortnite le bon jeu 2', 1523548806);
INSERT INTO `comments`(`user_id`, `post_id`, `message`, `date`) VALUES (1, 1, 'fortnite le bon jeu 2', 1523548806);
INSERT INTO `comments`(`user_id`, `post_id`, `message`, `date`) VALUES (1, 1, 'fortnite le bon jeu 2', 1523548806);
INSERT INTO `comments`(`user_id`, `post_id`, `message`, `date`) VALUES (1, 1, 'fortnite le bon jeu 2', 1523548806);
INSERT INTO `comments`(`user_id`, `post_id`, `message`, `date`) VALUES (1, 1, 'fortnite le bon jeu 2', 1523548806);
INSERT INTO `comments`(`user_id`, `post_id`, `message`, `date`) VALUES (1, 1, 'fortnite le bon jeu 2', 1523548806);
INSERT INTO `comments`(`user_id`, `post_id`, `message`, `date`) VALUES (1, 1, 'fortnite le bon jeu 2', 1523548806);
INSERT INTO `comments`(`user_id`, `post_id`, `message`, `date`) VALUES (1, 1, 'fortnite le bon jeu 2', 1523548806);
INSERT INTO `comments`(`user_id`, `post_id`, `message`, `date`) VALUES (1, 1, 'fortnite le bon jeu 2', 1523548806);
